export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST"
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS"
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR"

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST"
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS"
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR"

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST"
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR"

export const VIEW_EMPLOYEE_REQUEST = "VIEW_EMPLOYEE_REQUEST"
export const VIEW_EMPLOYEE_SUCCESS = "VIEW_EMPLOYEE_SUCCESS"
export const VIEW_EMPLOYEE_ERROR = "VIEW_EMPLOYEE_ERROR"

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR"