export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST"
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS"
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR"

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST"
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS"
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR"